# VoidBR Limine theme
# Author: Vilmar Catafesta <vcatafesta@gmail.com>

TIMEOUT: 3
VERBOSE: no
term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89e2b4;f5c2e7;94e2d5;cdd6f4
term_background: ffffffff
term_foreground: cdd6f4
term_background_bright: ffffffff
term_foreground_bright: cdd6f4
interface_branding:
wallpaper: boot():/limine/voidbr-tokyonight.png
wallpaper_style: stretched

/VoidBR (Kernel 7.1.8_1)
    PROTOCOL: linux
    PATH: boot():/limine/vmlinuz-7.1.8_1
    MODULE_PATH: boot():/limine/initramfs-7.1.8_1.img
    CMDLINE: root=UUID=ac954a47-680a-4876-a35a-c473af4c6ecf rw loglevel=4

/VoidBR (Kernel 7.0.14_1)
    PROTOCOL: linux
    PATH: boot():/limine/vmlinuz-7.0.14_1
    MODULE_PATH: boot():/limine/initramfs-7.0.14_1.img
    CMDLINE: root=UUID=ac954a47-680a-4876-a35a-c473af4c6ecf rw loglevel=4

/VoidBR (Kernel 6.19.14_1)
    PROTOCOL: linux
    PATH: boot():/limine/vmlinuz-6.19.14_1
    MODULE_PATH: boot():/limine/initramfs-6.19.14_1.img
    CMDLINE: root=UUID=ac954a47-680a-4876-a35a-c473af4c6ecf rw loglevel=4

/VoidBR (Kernel 6.18.44_1)
    PROTOCOL: linux
    PATH: boot():/limine/vmlinuz-6.18.44_1
    MODULE_PATH: boot():/limine/initramfs-6.18.44_1.img
    CMDLINE: root=UUID=ac954a47-680a-4876-a35a-c473af4c6ecf rw loglevel=4

/VoidBR (Kernel 6.12.103_1)
    PROTOCOL: linux
    PATH: boot():/limine/vmlinuz-6.12.103_1
    MODULE_PATH: boot():/limine/initramfs-6.12.103_1.img
    CMDLINE: root=UUID=ac954a47-680a-4876-a35a-c473af4c6ecf rw loglevel=4

/VoidBR (Kernel 5.10.264_1)
    PROTOCOL: linux
    PATH: boot():/limine/vmlinuz-5.10.264_1
    MODULE_PATH: boot():/limine/initramfs-5.10.264_1.img
    CMDLINE: root=UUID=ac954a47-680a-4876-a35a-c473af4c6ecf rw loglevel=4

